import { fileURLToPath, URL } from 'node:url'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

/**
 * Two builds come out of this config.
 *
 *   pnpm build:client -> dist/client  (the SPA shell + the storefront's hydration
 *                                      bundle, with a manifest so the server can
 *                                      find the hashed filenames)
 *   pnpm build:server -> dist/server  (the storefront's SSR renderer, for Node)
 *
 * `isSsrBuild` is passed by Vite when `--ssr` is used, which is what distinguishes
 * them — the alternative, a second config file, duplicates the plugin and alias
 * setup and then drifts from it.
 */
export default defineConfig(({ isSsrBuild }) => ({
  plugins: [react(), tailwindcss()],
  /**
   * Bundle the SSR renderer's dependencies instead of leaving them as bare
   * imports.
   *
   * Vite externalises node_modules for an SSR build, on the assumption that the
   * server runs next to its own `node_modules`. A serverless host ships only
   * what it traced from the function entry, and it cannot trace a path this
   * server builds at runtime — so `dist/server/entry-server.js` arrived alone
   * and every request died on `Cannot find package 'react'`. Self-contained is
   * also the honest shape for a build artefact that is copied somewhere else.
   */
  ssr: { noExternal: true },
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    port: 5173,
    // Storefronts resolve by subdomain ({slug}.selld.ph). Allow wildcard hosts in
    // dev so `foo.localhost:5173` reaches the same server as the dashboard.
    host: true,
    /**
     * `/api/*` lives on the Node server, not here.
     *
     * In production one process serves both the dashboard shell and these routes,
     * so the dashboard can just fetch a relative path. In dev the dashboard is on
     * Vite and the API is on `pnpm dev:store`, so without this proxy every courier
     * booking 404s — and only in development, which is the worst place for a
     * difference like that to hide.
     */
    proxy: {
      '/api': {
        target: process.env.STOREFRONT_ORIGIN ?? 'http://127.0.0.1:5174',
        changeOrigin: true,
      },
    },
  },
  build: {
    // Sellers are on mid-range Android phones over mobile data. The storefront
    // carries the stricter budget — see docs/phase-status.md.
    chunkSizeWarningLimit: 600,
    sourcemap: true,
    ...(isSsrBuild
      ? {
          outDir: 'dist/server',
          // Not minified: this runs in Node, where the only cost of readable
          // output is disk, and a legible stack trace from a failed production
          // render is worth more than that.
          minify: false,
        }
      : {
          outDir: 'dist/client',
          // The server reads this to resolve the storefront entry's hashed
          // filename and its stylesheet.
          manifest: true,
          rollupOptions: {
            input: {
              // The dashboard SPA, still entirely client-rendered.
              app: fileURLToPath(new URL('./index.html', import.meta.url)),
              // The storefront's hydration entry, built as its own input: the
              // storefront's HTML is generated by the server, so nothing reaches
              // this module from index.html.
              storefront: fileURLToPath(
                new URL('./src/storefront/entry-client.tsx', import.meta.url),
              ),
            },
          },
        }),
  },
}))
